source 'https://rubygems.org'

gem 'puma'
gem 'rails'
gem 'sidekiq', path: '..'

# Ubuntu required packages to install rails
# apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev libsqlite3-dev
platforms :ruby do
  gem 'sqlite3'
end
